### ISSUE TITLE
License change, CLA

### ISSUE THREAD

**Issue by alexander-potemkin** [get-zen-dev/Devneya-CookieCode#5]
Please confirm the license change (LICENSE) and your agreement with the contributor license agreement (CONTRIBUTOR_LICENSE_AGREEMENT).

Please, respond to the ticket with the following statement: 'I have read the license - LICENSE and the contributor license agreement (CLA Document) - CONTRIBUTOR_LICENSE_AGREEMENT and I hereby sign the CLA and accept the License change for all my previous and future commits'.

**Comment by Setom29** [comment]
I have read the license - LICENSE and the contributor license agreement (CLA Document) - CONTRIBUTOR_LICENSE_AGREEMENT and I hereby sign the CLA and accept the License change for all my previous and future commits.

**Comment by IgorianKiselev02** [comment]
I have read the license - LICENSE.MD and the contributor license agreement (CLA Document) - CONTRIBUTOR_LICENSE_AGREEMENT and I hereby sign the CLA and accept the License change for all my previous and future commits.

**Comment by Mell0r** [comment]
I have read the license - LICENSE and the contributor license agreement (CLA Document) - CONTRIBUTOR_LICENSE_AGREEMENT and I hereby sign the CLA and accept the License change for all my previous and future commits.

**Comment by ArtyomPeshkov** [comment]
I have read the license - LICENSE and the contributor license agreement (CLA Document) - СONTRIBUTOR_LICENSE_AGREEMENT and I hereby sign the CLA and accept the License change for all my previous and future commits.

**Comment by alexander-potemkin** [comment]
Thanks everyone.
